### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by ghost** [openlgtv/wiki#1]

**Comment by smx-smx** [comment]
Yes, i'm aware, but i'm not the site or the domain owner.
Since the original community was long dead, i created a Discord group and i created this github organization.

This repository is an attempt to mirror the original site from a backup i made back when the site was accessible.
Not all contents is here or as accessible as the original site, but i don't have the time to clean it up.

**Comment by ghost** [comment]
Oh ok

joi, 24 dec. 2020, 16:49 smx <notifications@github.com> a scris:
